baseURL = "http://example.org/"
languageCode = "en-us"
title = "Just Thai Kitchen"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  facebook = "tt"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "tt"
